[project]
name = "bitnode"
version = "0.0.1"
description = ""
authors = [
    { name = "Pradyumna Krishna", email = "git@onpy.in" },
]
dependencies = [
    "fastapi==0.89.1",
    "uvicorn[standard]==0.20.0",
    "jinja2==3.1.2",
]

[project.optional-dependencies]
dev = ["pytest", "pylint"]
